[[plugins]]
package = "@netlify/plugin-gatsby"

[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  framework = "gatsby"
  functions = "netlify/functions"
  publish = "public"
  port = 8888

